### ISSUE TITLE
Installation of plugin under Windows 10 doesnt work

### ISSUE THREAD

**Issue by kramerdog** [jimmycuadra/vagrant-sprinkle#5]
Cant get the sprinkle provisioner to work in my Vagrantfile under Windows 10.

I was expecting the plugin install to do everything but even with installing sprinkle explicitly under vagrant/embedded it still doesnt work.

There seems to be gems everywhere, which is confusing to me. Any ideas wha's wrong?

Step 1

`vagrant plugin install vagrant-sprinkle`

installed under

    C:\Users\Craig\.vagrant.d\gems\2.3.4\gems

Vagrantfile
	
```
          development.vm.provision(:sprinkle) do |sprinkle|
            sprinkle.script = '../sprinkle/setup_vm.rb'
            sprinkle.cloud = true
            sprinkle.verbose = true
          end
```
		  
`vagrant up`
		  
```
==> vm: Running provisioner: sprinkle...
C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'sprinkle' (>= 0) among 46 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=C:/HashiCorp/Vagrant/embedded/gems', execute `gem env` for more information
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/dependency.rb:320:in `to_spec'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from C:/Ruby200-x64/bin/sprinkle:22:in `<main>'	
```	  

`gem env`

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.4 (2017-03-30 patchlevel 301) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/HashiCorp/Vagrant/embedded/gems
  - USER INSTALLATION DIRECTORY: C:/Users/Craig/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: C:/HashiCorp/Vagrant/embedded/mingw64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/HashiCorp/Vagrant/embedded/gems/bin
  - SPEC CACHE DIRECTORY: C:/Users/Craig/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/HashiCorp/Vagrant/embedded/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\HashiCorp\Vagrant\embedded\mingw64\bin
     - C:\HashiCorp\Vagrant\embedded\usr\bin
```
Step 2

Install sprinkle gem in vagrant's embedded Ruby as Admin user

    `C:\HashiCorp\Vagrant\embedded\mingw64\bin\gem install sprinkle`

which installs to

    `C:\HashiCorp\Vagrant\embedded\mingw64\lib\ruby\gems\2.3.0\gems`
	
`vagrant up	`	  
	
```
	c:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem sprinkle (>= 0.a) (Gem::GemNotFoundException)
        from C:/HashiCorp/Vagrant/embedded/mingw64/bin/sprinkle:24:in `<main>'
```

Step 3
		
Copy sprinkle.rb from C:\HashiCorp\Vagrant\embedded\mingw64\lib\ruby\gems\2.3.0\gems to

    `C:\HashiCorp\Vagrant\embedded\gems\gems`

Copy sprinkle-0.7.7.gemspec from C:\HashiCorp\Vagrant\embedded\mingw64\lib\ruby\gems\2.3.0\specifications to

    `C:\HashiCorp\Vagrant\embedded\gems\specifications`

`vagrant up`
		  

```
c:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- active_support/all (LoadError)
        from c:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/sprinkle-0.7.7/lib/sprinkle.rb:2:in `<top (required)>'
        from c:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from c:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/sprinkle-0.7.7/bin/sprinkle:96:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/bin/sprinkle:26:in `load'
        from C:/HashiCorp/Vagrant/embedded/mingw64/bin/sprinkle:26:in `<main>'
```

**Comment by krinkel** [comment]
Fixed by doing this https://stackoverflow.com/questions/26141589/gem-install-error-sass-compass/26244869#26244869
